# Generated by Django 6.1.1 on 2026-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_poster_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='ЧПУ для адреса: /halls/depo/', max_length=120, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='ЧПУ для адреса: /afisha/kviz-60-sekund/', max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
